apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: food-app
        image: naveena818/food-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "Production-EKS"
---
apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  type: LoadBalancer
  selector:
    app: food-app
  ports:
  - port: 80
    targetPort: 5000